steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.gpu
      - --build-arg
      - COMPRESSOR_MODEL=${_COMPRESSOR_MODEL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:latest

substitutions:
  _REGION: us-central1
  _REPO: prompt-compression
  _SERVICE: prompt-compression-gpu
  _COMPRESSOR_MODEL: microsoft/llmlingua-2-bert-base-multilingual-cased-meetingbank
